<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Fri, 19 Jan 2024 18:24:18 GMT</lastBuildDate>
    <item>
      <title>尝试验证我的域时收到“帐户未授权错误”消息</title>
      <link>https://community.openai.com/t/i-get-a-not-authorized-for-account-error-when-trying-to-verify-my-domain/592787#post_16</link>
      <description><![CDATA[对我来说同样的问题，尝试添加我的域时新的 customgpt]]></description>
      <guid>https://community.openai.com/t/i-get-a-not-authorized-for-account-error-when-trying-to-verify-my-domain/592787#post_16</guid>
      <pubDate>Fri, 19 Jan 2024 18:19:13 GMT</pubDate>
    </item>
    <item>
      <title>自定义 GPT 错误 - 超链接不可点击</title>
      <link>https://community.openai.com/t/custom-gpt-bug-hyperlinks-not-clickable/565499?page=2#post_36</link>
      <description><![CDATA[


米古鲁：
&lt;块引用&gt;
GPT 显示超链接，但无法点击。


谢谢。
可以确认链接不可点击，因为它们不是正确的链接。
在 Chrome 中使用 F12 检查链接。
&lt;a target=&quot;_new&quot;&gt;非常适合您的需求&lt;/a&gt;
]]></description>
      <guid>https://community.openai.com/t/custom-gpt-bug-hyperlinks-not-clickable/565499?page=2#post_36</guid>
      <pubDate>Fri, 19 Jan 2024 18:17:36 GMT</pubDate>
    </item>
    <item>
      <title>Playground <> API 响应（所有参数相同）</title>
      <link>https://community.openai.com/t/playground-api-response-all-params-equal/591034#post_11</link>
      <description><![CDATA[@mellisa - 我在提交之前逐一比较了每个字符确定绝对是零差异，仔细检查了所有内容，但仍然有问题。
过去，有些人建议升级你的 Python 模块
pip 安装升级 openai

当前版本是1.8.0。
这个建议对我来说没有意义，因为它只是一个非常简单的包装器，应该没有任何效果。
还要确保您使用相同的字符串，方法是暂时使用静态字符串，并使用 Playground 右上角的“查看代码”按钮直接从 Playground 复制它。

如果这有帮助，请检查字符串中是否存在未转换的引号或未转换的换行符 (\n) 等内容。
如果您有更多信息，我可以帮助您了解更多想法 ]]></description>
      <guid>https://community.openai.com/t/playground-api-response-all-params-equal/591034#post_11</guid>
      <pubDate>Fri, 19 Jan 2024 18:16:03 GMT</pubDate>
    </item>
    <item>
      <title>将 AI 上下文扩展到本地文档之外</title>
      <link>https://community.openai.com/t/expand-ai-context-beyound-local-documentation/593894#post_1</link>
      <description><![CDATA[您好，我使用 langchain 制作了一个 openai 模型，它将与我的文档进行通信，但是我有一个问题，我希望模型的行为是这样的，如果它在文档中找不到问题，请查阅其一般信息知识，我这是什么意思？
假设我有两个模型，一个是聊天模型，另一个使用矢量存储并从文件中读取。
我询问基本聊天模型德国的主要城市是什么，它回答了柏林。
我问基于文档的模型相同的问题，它检查文档发现它没有信息，那么它应该像基本聊天模型一样运行，并使用自己的工具集找到答案。但我得到的只是答案不在提供的上下文中。

这是我使用的代码
**mods.py**

def parse_pdf(file_path: str) -&gt;;列表[字符串]：
将 open(file_path, &quot;rb&quot;) 作为 f：
    数据 = f.read()

pdf = PdfReader(BytesIO(数据))
输出=[]


对于 pdf.pages 中的页面：
    文本 = page.extract_text()
    文本 = re.sub(r&quot;(\w+)-\n(\w+)&quot;, r&quot;\1\2&quot;, 文本)
    text = re.sub(r&quot;(?;列表[字符串]：
组合文本 = &#39; &#39;.join(文本)
text_splitter = RecursiveCharacterTextSplitter(
    块大小=2000，
    分隔符=[&quot;\n\n&quot;, &quot;\n&quot;, &quot;.&quot;, &quot;!&quot;, &quot;?&quot;, &quot;,&quot;, &quot; &quot;, &quot;&quot;],
    块重叠=100，
）
块 = text_splitter.split_text(combined_text)
返回块


 **主.py**

 所有文本 = []
    对于 pdf_files 中的 pdf_file：
        file_path = os.path.join(data_path, pdf_file)
        尝试：
            文本 = mods.parse_pdf(文件路径)
            all_texts.extend(文本)
        除了文件未找到错误：
            st.error(f&quot;未找到文件：{file_path}&quot;)
            返回
        除了异常 e：
            st.error(f&quot;读取 PDF 时发生错误：{e}&quot;)

  文档 = mods.text_to_docs(all_texts)
  嵌入 = OpenAIEmbeddings()
  矢量存储= FAISS.from_texts（文档，嵌入=嵌入）
  llm = ChatOpenAI(温度=0.3, max_tokens=1000, model_name=&quot;gpt-4-1106-preview&quot;)
  qa = ConversationalRetrievalChain.from_llm(llm=llm,retriever=vector_store.as_retriever())

  如果“消息”不在 st.session_state 中：
        st.session_state.messages = []
  如果不是 st.session_state.messages：
        welcome_message = {&quot;role&quot;: &quot;助理&quot;, &quot;content&quot;: &quot;您好，需要什么帮助吗？&quot;}
        st.session_state.messages.append(welcome_message)

  对于 st.session_state.messages 中的消息：
        与 st.chat_message(message[&quot;role&quot;]):
            st.markdown(消息[“内容”])

  if prompt := st.chat_input(&quot;你的问题是什么&quot;):
        st.session_state.messages.append({&quot;角色&quot;: &quot;用户&quot;, &quot;内容&quot;: 提示})
        与 st.chat_message(“用户”)：
            st.markdown（提示）

        result = qa({&quot;question&quot;: 提示, &quot;chat_history&quot;: [(message[&quot;role&quot;], message[&quot;content&quot;]) for message in st.session_state.messages]})

        与 st.chat_message(“助理”)：
            full_response = 结果[“答案”]
            st.markdown（完整响应）
        st.session_state.messages.append({&quot;角色&quot;: &quot;助理&quot;, &quot;内容&quot;: full_response})
]]></description>
      <guid>https://community.openai.com/t/expand-ai-context-beyound-local-documentation/593894#post_1</guid>
      <pubDate>Fri, 19 Jan 2024 18:11:24 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT 员工对无响应的支持和帐户封锁感到沮丧</title>
      <link>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_6</link>
      <description><![CDATA[您唯一能做的就是通过 help.openai.com 右下角的气泡发送电子邮件以寻求支持。可能需要几周时间才能得到回复。]]></description>
      <guid>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_6</guid>
      <pubDate>Fri, 19 Jan 2024 18:11:02 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT 员工对无响应的支持和帐户封锁感到沮丧</title>
      <link>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_5</link>
      <description><![CDATA[不，我从不使用VPN，这是那边的问题，它没有被黑客攻击，而是被停用了]]></description>
      <guid>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_5</guid>
      <pubDate>Fri, 19 Jan 2024 18:07:28 GMT</pubDate>
    </item>
    <item>
      <title>自定义 GPT 错误 - 超链接不可点击</title>
      <link>https://community.openai.com/t/custom-gpt-bug-hyperlinks-not-clickable/565499?page=2#post_35</link>
      <description><![CDATA[我们这里也有同样的问题：
  &lt;标题类=“来源”&gt;
      
ChatGPT


  &lt;文章类=“onebox-body”&gt;
    ChatGPT - Empleos Chile 由米古鲁
智利最优秀的虚拟巴士公司。 En miguru.ai tenemos todas las ofertas。





GPT 显示超链接，但无法点击。]]></description>
      <guid>https://community.openai.com/t/custom-gpt-bug-hyperlinks-not-clickable/565499?page=2#post_35</guid>
      <pubDate>Fri, 19 Jan 2024 18:06:14 GMT</pubDate>
    </item>
    <item>
      <title>GPT-4 的实际截止日期是哪一天？</title>
      <link>https://community.openai.com/t/what-is-the-actual-cutoff-date-for-gpt-4/394750#post_21</link>
      <description><![CDATA[不要相信模型。 ]]></description>
      <guid>https://community.openai.com/t/what-is-the-actual-cutoff-date-for-gpt-4/394750#post_21</guid>
      <pubDate>Fri, 19 Jan 2024 17:59:11 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT 员工对无响应的支持和帐户封锁感到沮丧</title>
      <link>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_4</link>
      <description><![CDATA[您所在的国家/地区允许使用 OpenAI 的服务，因此我唯一的猜测是您的帐户被黑客入侵或您使用了 VPN。]]></description>
      <guid>https://community.openai.com/t/frustrations-with-unresponsive-support-and-account-blockage-by-chatgpt-staff/593313#post_4</guid>
      <pubDate>Fri, 19 Jan 2024 17:55:01 GMT</pubDate>
    </item>
    </channel>
</rss>